### ISSUE TITLE
Creating a "Perlanet" GitHub Organization

### ISSUE THREAD

**Issue by rwp0** [davorg/perl-perlanet-docker#1]
I think with [Perlanet](https://github.com/davorg/perlanet), its [configuration](https://github.com/davorg/planetperl), and [this](https://github.com/davorg/perl-perlanet-docker) Docker image you can (or rather somewhat _should_) create a GitHub [organization](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/about-organizations) to group all these repositories together under the **Perlanet** name when have time.

This will be linked to your GitHub user as the real owner of the repositories.

The transfer (after creating the `perlanet` organization) can be done either with the GH UI or using [GH CLI](https://cli.github.com/) with commands below:

```
gh api repos/davorg/perlanet/transfer -f new_owner=perlanet
gh api repos/davorg/planetperl/transfer -f new_owner=perlanet
gh api repos/davorg/perl-perlanet-docker/transfer -f new_owner=perlanet
```

Thanks.

**Comment by davorg** [comment]
I see what you mean. But I'm not sure I agree.

* I agree that it's important to link Perlanet and the Docker image. But I think it's possible to do that more simply, by just moving the Docker files into the main Perlanet repo.
* Planet Perl isn't as tightly linked as the other two repos. It's one of a number of planets that I run using Perlanet. And I'd like to encourage other people to build their own (or, at least, that was the plan before web feeds basically died out).

Maybe I can add a list of "Built with Perlanet" sites in the Perlanet repo. And finally get round to building the Perlanet web site that I've been thinking about for years.

**Comment by rwp0** [comment]
Okay, thanks.

---

My thought was that the GH organization is a GitHub way of grouping related things (be it a bit loosely or very tightly),
and also allowing other people interested in a particular subject to find, and participate in the development/discussion etc thereof potentially becoming contributors and members letting the project grow continuosly.

Such a useful idea just seems to be scattered here and there, and therefore was hard to find Googling for me.

If not grouping on Planet Perl then grouping on Perlanet (with its many [instances](https://github.com/davorg?tab=repositories&q=perlanet&type=&language=&sort=)) could be an effort to organize things better IMHO.

Anyway thanks again for everything, and I just wanted to share my thoughs reading the reply.

The decision is yours as the author, and I do respect that.

**Comment by davorg** [comment]
I've built [this web site](https://theplanetarium.org/) that is [automatically built](https://github.com/davorg/theplanetarium/blob/main/bin/build) from the `perlanet` topic on GitHub.
